// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uawglncthemjdtzrkwbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhd2dsbmN0aGVtamR0enJrd2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjcxNzUsImV4cCI6MjA2NzY0MzE3NX0.HoDEAe3Ryic4s9ndhg50_wt7qb7VW8wsoVqRzvBvN4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});